version: '3.2'
services:
  server:
    build: ../engintl
    ports:
      - 8000:8000
    volumes:
      - ./test-server:/mnt/server
      - ./test-server/test.sh:/test.sh
      - ./django-payment:/mnt/payment
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 10.0.0.1

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      backend:
        ipv4_address: 10.0.0.2

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
