version: '3.2'
services:
  server:
    build: ./test-server
    command: sleep 10000000
    volumes:
      - ./test-server:/mnt/server
      - ./test-server/test.sh:/test.sh
      - ./:/mnt/payment
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 10.3.0.3

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      backend:
        ipv4_address: 10.3.0.2

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/16
