# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-15 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=16)),
                ('price', models.PositiveIntegerField()),
                ('buyers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
