# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-07 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
