# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-15 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECPayReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('MerchantID', models.CharField(max_length=10)),
                ('MerchantTradeNo', models.CharField(max_length=20)),
                ('RtnCode', models.IntegerField()),
                ('RtnMsg', models.CharField(blank=True, max_length=200)),
                ('TradeNo', models.CharField(max_length=20)),
                ('TradeAmt', models.IntegerField()),
                ('PaymentDate', models.DateTimeField()),
                ('PaymentType', models.CharField(max_length=20)),
                ('PaymentTypeChargeFee', models.FloatField()),
                ('TradeDate', models.DateTimeField()),
                ('SimulatePaid', models.IntegerField()),
                ('CheckMacValue', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
