# Generated by Django 4.2 on 2023-09-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecpayreceive',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
